# Generated by Django 4.0.5 on 2022-07-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersinfo', '0002_auto_20220701_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
